GENAVB_TSN_CONFIG:mx6-nxp-bsp = "endpoint_avb"
GENAVB_TSN_CONFIG:mx8-nxp-bsp = "endpoint_avb"
GENAVB_TSN_CONFIG:mx8mp-nxp-bsp = "endpoint_avb_tsn"
GENAVB_TSN_CONFIG:mx93-nxp-bsp = "endpoint_avb_tsn"
GENAVB_TSN_CONFIG:mx8dxl-nxp-bsp = "endpoint_avb_tsn"

GENAVB_TSN_TARGET:mx8-nxp-bsp = "linux_imx8"
GENAVB_TSN_TARGET:mx93-nxp-bsp = "linux_imx8"
GENAVB_TSN_TARGET:mx6-nxp-bsp = "linux_imx6"
GENAVB_TSN_TARGET:mx6ull-nxp-bsp = "linux_imx6ull"
